org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=defaulted
mod.archives_base=defaulted
mod.name=Defaulted
mod.description=Minecraft mod to enable in-game modification of default item components.
mod.group=net.atlas
mod.license=MIT
mod.version=1.3.8
mod.sub_version=release

deps.fabric-loader=0.19.5
deps.kaleido=0.3.3+1.3.2
deps.java_diff_version = 4.9
loomx.loom_version=1.17-SNAPSHOT

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=LxgPJAAy
publish.curseforge=1177694
#publish.additionalVersions=